# Generated by Django 2.2.19 on 2022-05-31 06:35

import brand.models
import category.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', category.fields.TitleCharField(max_length=64)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('thumbnail', models.ImageField(null=True, upload_to=brand.models.brand_thumbnail)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
