# Generated by Django 2.2.19 on 2022-06-05 12:13

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to=brand.models.brand_thumbnail),
        ),
    ]
