# Generated by Django 2.2.19 on 2021-11-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductVariantImage',
        ),
    ]
