# Generated by Django 2.2.19 on 2022-06-05 12:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to=product.models.product_thumbnail),
        ),
    ]
