# Generated by Django 2.2.19 on 2021-10-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Merchant'), ('C', 'Customer')], default='C', max_length=1),
        ),
    ]
