# Generated by Django 2.2.19 on 2021-08-13 15:29

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(upload_to=category.models.category_thumbnail),
        ),
    ]
