# Generated by Django 2.2.19 on 2021-11-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211127_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_varient',
            new_name='product_variant',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
